symfony_shop_catlalog_product:
    resource: "@SymfonyShopCatlalogBundle/Controller/ProductController.php"
    type:     annotation

symfony_shop_catlalog:
    resource: "@SymfonyShopCatlalogBundle/Resources/config/routing.xml"
    prefix:   /catalog

app:
    resource: '@AppBundle/Controller/'
    type: annotation

symfonyshop_catalog_category:
    resource: '@SymfonyShopCatalogBundle/Controller/CategoryController'
    type: annotation  

symfonyshop_catalog_product:
    resource: '@SymfonyShopCatalogBundle/Controller/ProductController'
    type: annotation   